travis:
  secure:
    BINSTAR_TOKEN: hmKXBFJMxit9WUFuQb6t7Q5jKU96JXs2FVKFess9RSIuOjv68P00HT2BxJpKGL8TYIV6rXz5H4cq30dl4zz3B+7WnafRNYCYgh5B7i4hXwUwqsOi3y/DxU8boeNDgrP8G4v8scfq1NnzDW9egTz0q6vdy+HvevWD/jYBNf0jDKheFTAsRK4i9eL9F6ZQqRHiejqyx5qLEEtLqlfN1oEI5hrWgORS9aTlBCmzdVTm30XNG6JM68jZ8j1cVGvM7kkDU3PTl1PFgke6tQSnflkolRQxBL+nhV4zNZfmqJZJQWQseKzGo8k9Wic1wcYZwJRiY8gmj2dTmX15WkjVUSE7OgRqSj7b2T5Zu9ZMiFbAII7ZU9WpWj4PZG12URPPUJaPTZnA238D36+bztioNGOkwe2U+ZrXnFKC0+R+bKPZrMWUxb9MiK/5sCkzon4VnFCDElqBchp/ivrhpOHaTveuFi3VVoErWuI/QNXfMJN9ygg/vK0lqWsBGStqfzTsC098e6yBN8/f+aYz+6TSIrCT7zDWs70uJPAsUV+nCC4chk/9Lg0H1tVT0Tfc5pOPf1LWsVMGNQ0C95zrzBpDL5dEbpA/Qqu3zcK07PsRsk254mNeIIZtYUzI+YKwVUb1zoCNF5z5paHNhOHgVqAgdiiUPdspHxpmuWNc5+3TxtymMho=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
